spring.application.name=soporte-tecnico-backend


#CREAR UN NUEVO PUERTO
 server.port=8080

#CONEXION A LA BASE DE DATOS
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
